name: rnaseq-rpb4
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core system
  - r-base=4.3.0

  # Bioinformatics tools
  - fastqc=0.11.9
  - trimmomatic=0.40
  - hisat2=2.2.1
  - subread=2.0.3
  - samtools=1.19
  - parallel
  - pigz

  # R packages
  - bioconductor-tidyverse
  - bioconductor-deseq2
  - bioconductor-pheatmap
  - bioconductor-ggplot2
  - bioconductor-org.sc.sgd.db
  - bioconductor-clusterprofiler
  - bioconductor-enrichplot
  - bioconductor-gridextra
  - bioconductor-data.table 
