name: rnaseq-rpb4
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core system
  - r-base=4.4.0

  # Bioinformatics tools
  - fastqc=0.11.9
  - trimmomatic=0.39
  - hisat2=2.2.1
  - featureCounts=2.0.3
  - samtools=1.13

  # R packages
  - r-tidyverse
  - r-DESeq2
  - r-pheatmap
  - r-ggplot2
  - r-org.sc.sgd.db
  - r-clusterProfiler
  - r-enrichplot
  - r-grid
  - r-gridExtra
