name: rnaseq-rpb4
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core system
  - r-base=4.3.0

  # Bioinformatics tools
  - fastqc=0.11.9
  - trimmomatic=0.40
  - hisat2=2.2.1
  - subread=2.0.3
  - samtools=1.13
  - parallel
  - pigvz

  # R packages
  - r-tidyverse
  - r-deseq2
  - r-pheatmap
  - r-ggplot2
  - r-org.sc.sgd.db
  - r-clusterprofiler
  - r-enrichplot
  - r-gridextra
  - r-data.table 
